apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{include "db.fullname" . }}
  name: {{include "db.fullname" . }}
spec:
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  selector:
    app: {{include "db.fullname" . }}
  type: {{.Values.service.type}}