apiVersion: v1
kind: Secret
metadata:
  name: {{include "db.fullname" . }}-secret
data:
  mongodb-username: {{.Values.secret.mongodb_username}}
  mongodb-password:  {{.Values.secret.mongodb_password}}
