apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{include "db.fullname" . }}-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.volume.storage}}