apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{.Release.Name}}-{{.Chart.Name}}
  name: {{.Release.Name}}-{{.Chart.Name}}
spec:
  {{with .Values.service}}    #this sets the scope of below properties to 
  type: {{.type}}               #  .Values.service.type 
  ports:
    - protocol: "TCP"
      port: {{.port}}           #  .Values.service.port 
      targetPort: 3000
      {{end}}
  selector:
    app: {{.Release.Name}}-{{.Chart.Name}}
 # type: NodePort