apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-{{.Chart.Name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Release.Name}}-{{.Chart.Name}} 
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-{{.Chart.Name}}
    spec:
      containers:
      - image: {{.Values.image.repo}}:{{.Values.image.tag}}
        imagePullPolicy: Always
        name: {{.Release.Name}}-{{.Chart.Name}}
        ports:
        - name: backend
          containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: {{.Release.Name}}-{{.Chart.Name}}-secret
              key: mongodb-uri