apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ include "backend.fullname" . }} 
  template:
    metadata:
      labels:
        app: {{ include "backend.fullname" . }}
    spec:
      containers:
      - image: {{.Values.image.repo}}:{{.Values.image.tag}}
        imagePullPolicy: Always
        name: {{ include "backend.fullname" . }}
        ports:
        - name: backend
          containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: {{ include "backend.fullname" . }}-secret
              key: mongodb-uri