backend:
   secret:
     mongodb_uri: 
        username: admin
        password: password
   ingress:
      enabled: false

frontend:
  ingress:
    enabled: false

ingress:
  hosts:
   - host:
       domain: frontend.local
       chart: frontend
   - host:
       domain: backend.local
       chart: backend